---
- hosts: webservers
  become: true
  tasks: 
    - name: install web components
      apt: name:{{item}} state=present update_cache=yes
      with_items:
       - apache2
       - python-pip
       - python-virtualenv
